import axios from 'axios';

const {
    REACT_APP_COMMON_DATA_SERVICE_PORT,
    REACT_APP_AUTHENTICATION_SERVICE_PORT,
    REACT_APP_SEARCH_SUGGESTION_SERVICE_PORT,
    SELLER_ACCOUNT_SERVICE_PORT,
    REACT_APP_COMMON_DATA_SERVICE_URL,
    REACT_APP_AUTHENTICATION_SERVICE_URL,
    REACT_APP_SEARCH_SUGGESTION_SERVICE_URL
} = process.env

export const authServiceAPI = axios.create({
<<<<<<< HEAD
    baseURL: REACT_APP_AUTHENTICATION_SERVICE_URL || `http://localhost:${REACT_APP_AUTHENTICATION_SERVICE_PORT}`
})

export const commonServiceAPI = axios.create({
    baseURL: REACT_APP_COMMON_DATA_SERVICE_URL || `http://localhost:${REACT_APP_COMMON_DATA_SERVICE_PORT}`
})

export const searchSuggestionServiceAPI = axios.create({
    baseURL: REACT_APP_SEARCH_SUGGESTION_SERVICE_URL || `http://localhost:${REACT_APP_SEARCH_SUGGESTION_SERVICE_PORT}`
=======
    baseURL: REACT_APP_AUTHENTICATION_SERVICE_URL || `http://3.110.133.64:${REACT_APP_AUTHENTICATION_SERVICE_PORT}`
})

export const commonServiceAPI = axios.create({
    baseURL: REACT_APP_COMMON_DATA_SERVICE_URL || `http://3.110.133.64:${REACT_APP_COMMON_DATA_SERVICE_PORT}`
})

export const searchSuggestionServiceAPI = axios.create({
    baseURL: REACT_APP_SEARCH_SUGGESTION_SERVICE_URL || `http://3.110.133.64:${REACT_APP_SEARCH_SUGGESTION_SERVICE_PORT}`
>>>>>>> 1f8e04bfa432040ab497598158b6dba5f1e666f4
})
